const GENRE_MAP: Record<string, string> = {
  'Action': 'Экшн',
  'Adventure': 'Приключения',
  'Avant Garde': 'Авангард',
  'Award Winning': 'Отмечено наградами',
  'Boys Love': 'Бойз-лав',
  'Comedy': 'Комедия',
  'Drama': 'Драма',
  'Ecchi': 'Этти',
  'Erotica': 'Эротика',
  'Fantasy': 'Фэнтези',
  'Girls Love': 'Гёрлз-лав',
  'Gourmet': 'Еда',
  'Harem': 'Гарем',
  'Horror': 'Ужасы',
  'Josei': 'Дзёсэй',
  'Kids': 'Детское',
  'Magic': 'Магия',
  'Mahou Shoujo': 'Махо-сёдзё',
  'Martial Arts': 'Боевые искусства',
  'Mecha': 'Меха',
  'Military': 'Военное',
  'Music': 'Музыка',
  'Mystery': 'Мистика',
  'Parody': 'Пародия',
  'Psychological': 'Психологическое',
  'Romance': 'Романтика',
  'Samurai': 'Самураи',
  'School': 'Школа',
  'Sci-Fi': 'Научная фантастика',
  'Seinen': 'Сэйнэн',
  'Shoujo': 'Сёдзё',
  'Shounen': 'Сёнэн',
  'Slice of Life': 'Повседневность',
  'Space': 'Космос',
  'Sports': 'Спорт',
  'Super Power': 'Сверхсилы',
  'Supernatural': 'Сверхъестественное',
  'Suspense': 'Триллер',
  'Vampire': 'Вампиры',
  'Work Life': 'Работа',
};

export function translateGenre(genre: string): string {
  return GENRE_MAP[genre] ?? genre;
}
